---
title: "Project 1 | Final Report"
author: "Franchesca Garcia, Jett Palmer, Kaatje Matthews-vanKoetsveld"
format: 
  html:
    toc: true
code-fold: show
embed-resources: true
editor: source
---

## Context

The Democracy and Dictatorship (DD) data were part of a TidyTuesday release on November 5th, 2024. TidyTuesday is a community-driven initiative that posts free, weekly datasets online for statisticians and data scientists to practice their data analysis skills. This release updates the data provided in "Regime types and regime change: A new dataset on democracy, coups, and political institutions" by Christian Bjørnskov and Martin Rode ([2020](https://link.springer.com/article/10.1007/s11558-019-09345-1)), with content borrowed from Cheibub et al. (2010) and Alvarex et al. (1996). Bjørnskov and Rode's paper was published in *The Review of International Organizations*, contributing to knowledge in academia and political science. The dataset, which focuses mainly on the presence or absence of democracy (or democratic principals), was then curated and posted on [GitHub](https://github.com/rfordatascience/tidytuesday/blob/main/data/2024/2024-11-05/readme.md) by Jon Harmon.

In their paper, Bjørnskov and Rode aimed to fill a gap in existing data on political regimes by adding additional countries, institutional details, and, importantly, an indicator of successful and failed coup d'états. They did this by selecting definitional criteria for coups and coding each observation accordingly. Specifically, "coups and coup attempts therefore have to \[fulfill\] the following definition to count as such in \[the\] dataset: First, the objective must be to overthrow the executive branch. Second, actors have to be previously linked to the state apparatus in some way. Third, a coup or coup attempt cannot last longer than a week at most." These data, among other things, can help us learn about the value of democracy by revealing the frequency and conditions under which a country adopts a non-democratic system and how long that intervention lasts. As stated, the DD data are more minimalistic, focusing on the presence or absence of democracy. Our analysis builds on the work of Bjørnskov and Rode by offering new unique data visualization and survival analysis of non-democratic "spells."

## Research Questions

1.  How long on average does it take countries that stopped being democratic to return to democracy?
2.  What factors influence the breaking of a non-democratic spell?

## Summaries & Visualizations

\[SANKEY PLOT\]

## Modeling

\[SURVIVAL MODEL\]
